# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FigureShow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1274, 199)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.l1 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l1.sizePolicy().hasHeightForWidth())
        self.l1.setSizePolicy(sizePolicy)
        self.l1.setMinimumSize(QtCore.QSize(100, 150))
        self.l1.setMaximumSize(QtCore.QSize(100, 150))
        self.l1.setStyleSheet("")
        self.l1.setText("")
        self.l1.setObjectName("l1")
        self.verticalLayout.addWidget(self.l1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.l2 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l2.sizePolicy().hasHeightForWidth())
        self.l2.setSizePolicy(sizePolicy)
        self.l2.setMinimumSize(QtCore.QSize(100, 150))
        self.l2.setMaximumSize(QtCore.QSize(100, 150))
        self.l2.setStyleSheet("")
        self.l2.setText("")
        self.l2.setObjectName("l2")
        self.verticalLayout_2.addWidget(self.l2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.l3 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l3.sizePolicy().hasHeightForWidth())
        self.l3.setSizePolicy(sizePolicy)
        self.l3.setMinimumSize(QtCore.QSize(100, 150))
        self.l3.setMaximumSize(QtCore.QSize(100, 150))
        self.l3.setStyleSheet("")
        self.l3.setText("")
        self.l3.setObjectName("l3")
        self.verticalLayout_3.addWidget(self.l3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.l4 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l4.sizePolicy().hasHeightForWidth())
        self.l4.setSizePolicy(sizePolicy)
        self.l4.setMinimumSize(QtCore.QSize(100, 150))
        self.l4.setMaximumSize(QtCore.QSize(100, 150))
        self.l4.setStyleSheet("")
        self.l4.setText("")
        self.l4.setObjectName("l4")
        self.verticalLayout_4.addWidget(self.l4)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.l5 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l5.sizePolicy().hasHeightForWidth())
        self.l5.setSizePolicy(sizePolicy)
        self.l5.setMinimumSize(QtCore.QSize(100, 150))
        self.l5.setMaximumSize(QtCore.QSize(100, 150))
        self.l5.setStyleSheet("")
        self.l5.setText("")
        self.l5.setObjectName("l5")
        self.verticalLayout_5.addWidget(self.l5)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_14 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_14.addWidget(self.label_14, 0, QtCore.Qt.AlignHCenter)
        self.r1 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r1.sizePolicy().hasHeightForWidth())
        self.r1.setSizePolicy(sizePolicy)
        self.r1.setMinimumSize(QtCore.QSize(100, 150))
        self.r1.setMaximumSize(QtCore.QSize(100, 150))
        self.r1.setStyleSheet("")
        self.r1.setText("")
        self.r1.setObjectName("r1")
        self.verticalLayout_14.addWidget(self.r1)
        self.horizontalLayout.addLayout(self.verticalLayout_14)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_11 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_11.addWidget(self.label_11, 0, QtCore.Qt.AlignHCenter)
        self.r2 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r2.sizePolicy().hasHeightForWidth())
        self.r2.setSizePolicy(sizePolicy)
        self.r2.setMinimumSize(QtCore.QSize(100, 150))
        self.r2.setMaximumSize(QtCore.QSize(100, 150))
        self.r2.setStyleSheet("")
        self.r2.setText("")
        self.r2.setObjectName("r2")
        self.verticalLayout_11.addWidget(self.r2)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_13 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_13.addWidget(self.label_13, 0, QtCore.Qt.AlignHCenter)
        self.r3 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r3.sizePolicy().hasHeightForWidth())
        self.r3.setSizePolicy(sizePolicy)
        self.r3.setMinimumSize(QtCore.QSize(100, 150))
        self.r3.setMaximumSize(QtCore.QSize(100, 150))
        self.r3.setStyleSheet("")
        self.r3.setText("")
        self.r3.setObjectName("r3")
        self.verticalLayout_13.addWidget(self.r3)
        self.horizontalLayout.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_12 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_12.addWidget(self.label_12, 0, QtCore.Qt.AlignHCenter)
        self.r4 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r4.sizePolicy().hasHeightForWidth())
        self.r4.setSizePolicy(sizePolicy)
        self.r4.setMinimumSize(QtCore.QSize(100, 150))
        self.r4.setMaximumSize(QtCore.QSize(100, 150))
        self.r4.setStyleSheet("")
        self.r4.setText("")
        self.r4.setObjectName("r4")
        self.verticalLayout_12.addWidget(self.r4)
        self.horizontalLayout.addLayout(self.verticalLayout_12)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_15 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_15.addWidget(self.label_15, 0, QtCore.Qt.AlignHCenter)
        self.r5 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.r5.sizePolicy().hasHeightForWidth())
        self.r5.setSizePolicy(sizePolicy)
        self.r5.setMinimumSize(QtCore.QSize(100, 150))
        self.r5.setMaximumSize(QtCore.QSize(100, 150))
        self.r5.setStyleSheet("")
        self.r5.setText("")
        self.r5.setObjectName("r5")
        self.verticalLayout_15.addWidget(self.r5)
        self.horizontalLayout.addLayout(self.verticalLayout_15)
        self.verticalLayout_16.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "左手大拇指"))
        self.label_2.setText(_translate("Dialog", "左手食指"))
        self.label_3.setText(_translate("Dialog", "左手中指"))
        self.label_4.setText(_translate("Dialog", "左手无名指"))
        self.label_5.setText(_translate("Dialog", "左手小拇指"))
        self.label_14.setText(_translate("Dialog", "右手大拇指"))
        self.label_11.setText(_translate("Dialog", "右手食指"))
        self.label_13.setText(_translate("Dialog", "右手中指"))
        self.label_12.setText(_translate("Dialog", "右手无名指"))
        self.label_15.setText(_translate("Dialog", "右手小拇指"))

import resource_rc
